name: Update Rating Chart

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests matplotlib
      
    - name: Generate rating chart
      run: python chess_rating.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # Принудительно синхронизируем с удалённым репозиторием
        git fetch origin
        git reset --hard origin/main
        
        # Генерируем график ещё раз на случай конфликтов
        python chess_rating.py
        
        # Добавляем и коммитим изменения
        git add rating_chart.png
        git commit -m "Update Lichess rating graph [skip ci]" || echo "No changes to commit"
        
        # Пушим изменения
        git push origin main
