name: Update Rating Chart

on:
  schedule:
    # Запускать каждый день в 12:00 UTC (15:00 по Москве)
    - cron: '0 12 * * *'
  workflow_dispatch:  # Разрешить ручной запуск

jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests matplotlib
      
    - name: Generate rating chart
      run: python generate_chart.py  # Ваш скрипт с кодом
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add rating_chart.png
        git commit -m "Auto-update rating chart" || echo "No changes to commit"
        git push
