name: Update Chess Rating Graph

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:  

jobs:
  update-graph:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests matplotlib

    - name: Run chess rating graph script
      run: |
        python chess_rating.py  # Запускаем скрипт для обновления графика

    - name: Commit and push updated graph
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add rating_chart.png
        git commit -m "Update chess rating graph"
        git push
