name: Update Rating Chart

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Важно: получает всю историю коммитов

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests matplotlib
      
    - name: Generate rating chart
      run: python generate_chart.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git pull --rebase  # Синхронизируем изменения
        git add rating_chart.png
        git commit -m "Update Lichess rating graph [skip ci]"
        git push
